general/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
	url(r'^event_list/(?P<pk>[\w\-]+)', views.EventListView.as_view(), name="event_list"),
	url(r'^category_list/', views.CategoryListView.as_view(), name="category_list"),
	url(r'^dashboard/', views.DashboardView.as_view(), name="dashboard"),
    url(r'^event_scanner/', views.event_scanner, name="event_scanner"),
	url(r'^event_attended/(?P<code>[\w\-]+)', views.event_attended, name="event_attended"),

	url(r'^$', views.IndexView.as_view(), name="index"),
	url(r'^year/2018', views.Year2018.as_view(), name="year_2018"),
	url(r'^year/2017', views.Year2017.as_view(), name="year_2017"),
]

utsaha_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^marketing/', include('marketing.urls')),
    url(r'^', include('general.urls')),
    url(r'^accounting/', include('accounting.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

general/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Department(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name


class User(AbstractUser):
	'''
	User: Holds details about the user.
	'''
	phone = models.CharField("Phone", max_length=15, null=True, blank=True)
	sem = models.IntegerField("Semester", null=True, blank=True)
	department = models.ForeignKey("Department", on_delete=models.CASCADE, null=True)
	amount = models.DecimalField(default=0.0, max_digits=50, decimal_places=2, null=True)

	def is_admin(self):
		return self.groups.filter(name='Admin').exists()

	def is_finance(self):
		return self.groups.filter(name='Finance').exists()

	def is_event_coordinator(self):
		return self.groups.filter(name='Event Coordinator').exists()

	def is_marketing_coordinator(self):
		return self.groups.filter(name='Marketing Coordinator').exists()


class Category(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name


class Event(models.Model):
	'''
	Event Details
	'''
	name = models.CharField("Name", max_length=50)
	description = models.TextField()
	price = models.DecimalField(max_digits=10, decimal_places=2)
	coordinator = models.ForeignKey("User")
	category = models.ForeignKey("Category")
	date = models.DateField()
	time = models.TimeField()
	venue = models.CharField(max_length=50)
	total_count = models.PositiveIntegerField(default=0)
	# max registrations per event and whether or not to enforce that
	max_count = models.PositiveIntegerField(help_text="Max no. of registrations in an event")
	is_enforced = models.BooleanField()

	def __str__(self):
		if self.is_enforced:
			return "%s (%s) - left(%s)"%(self.name, str(self.price), str(self.max_count))
		return "%s (%s)"%(self.name, str(self.price))


class Registration(models.Model):
	'''
	Details of person registering for an event
	'''
	event = models.ForeignKey("Event")
	name = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	phone_no = models.CharField(max_length=10)
	college = models.CharField(max_length=50)

	CASH="cash"
	PAYTM = "paytm"

	PAYMENT_CHOICES = ((CASH, "CASH"), (PAYTM, "PAYTM"))
	payment = models.CharField(max_length=5, choices=PAYMENT_CHOICES)
	agent = models.ForeignKey("User")
	is_attended = models.BooleanField(default=False)
	code = models.CharField(max_length=15, null=True, blank=True)
	date_created = models.DateField(auto_now_add=True, null=True)

	def __str__(self):
		return self.code

	def gen_code(self):
		return "100" + str(self.pk)

	def save(self, *args, **kwargs):
		if not self.pk:
			if self.event.is_enforced:
				self.event.max_count -= 1
				self.event.total_count += 1
				self.event.save()
		super(Registration, self).save(*args, **kwargs)
		

# from django.db.models.signals import post_save
# from django.dispatch import receiver

@receiver(post_save, sender=Registration)
def gen_code(sender, instance, **kwargs):
	instance.agent.amount += instance.event.price
	instance.agent.save()

templates/partials/navbar.html
 <div class="logo">
                <a href="#" class="simple-text">
                    {{user.first_name}}
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li>
                        <a href="{% url "dashboard" %}">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url "marketing_register" %}">
                            <i class="material-icons">library_books</i>
                            <p>Register</p>
                        </a>
                    </li>
                    {% if user.is_admin or user.is_finance %}
                    <li>
                        <a href="{% url "finance" %}">
                            <i class="material-icons">location_on</i>
                            <p>Finance</p>
                        </a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="{% url "category_list" %}">
                            <i class="material-icons text-gray">event</i>
                            <p>Events</p>
                        </a>
                    </li>
                    {% if user.is_admin or user.is_event_coordinator %}
                    <li>
                        <a href="{% url "event_scanner" %}">
                            <i class="material-icons text-gray">scanner</i>
                            <p>Scan</p>
                        </a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="{% url "marketing_finance" %}">
                            <i class="material-icons text-gray">location_on</i>
                            <p>Marketing Finances</p>
                        </a>
                    </li>
                    {% if user.is_admin or user.is_event_coordinator %}
                    <li>
                        <a href="{% url "registration_list" %}">
                            <i class="material-icons text-gray">library_books</i>
                            <p>Registration List</p>
                        </a>
                    </li>
                    {% endif %}

                    <li class="active-pro active">
                        <a target="blank" href="https://www.devxlabs.co">
                            <img width="30" src="https://www.bmsit.ac.in/devx.png">
                            <span>Powered By DevX</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> UTSAHA </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <div id="drop-div" class="dropdown">
                                    <button id="drop-btn" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><i class="material-icons">person</i>
                                    <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url "logout" %}">Logout</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>